name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install test dependencies
        run: python -m pip install -U pytest pytest-asyncio networkx 

      - name: Install project
        run: python -m pip install -e .

      - name: Run tests
        run: python -m pytest -q
