name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    name: tests (${{ matrix.os }} / py${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install PyYAML
          python -m pip install -e ".[dev,cron]"

      - name: Ruff
        run: python -m ruff check .

      - name: Black
        run: python -m black --check .

      - name: Mypy
        run: python -m mypy tm

      - name: Pytest
        run: python -m pytest -q

      - name: Run M1 demos (Linux only)
        if: runner.os == 'Linux'
        run: |
          chmod +x scripts/validate_examples.sh
          scripts/validate_examples.sh
        shell: bash

  no-sqlite:
    name: tests (NO_SQLITE)
    runs-on: ubuntu-latest
    env:
      NO_SQLITE: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install PyYAML
          python -m pip install -e ".[dev,cron]"

      - name: Pytest
        run: python -m pytest -q
